### ISSUE TITLE
Automatically assign roles and create service instances using Booster is failing to Assign Role Collection

### ISSUE THREAD

**Issue by VinayakTamse01** [sap-tutorials/Tutorials#20398]
Hi,

In Tutorial 1 : https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
in Step 4 : Automatically assign roles and create service instances using Booster is failing to assign Role Collection

Please Refer the Screenshot below

Actual Result:

![Starter1](https://user-images.githubusercontent.com/108262863/201004624-1b49ea33-6c06-4b13-9808-5c575f250006.png)

![Starter2](https://user-images.githubusercontent.com/108262863/201004653-4519a142-e72f-4e44-b046-b53304ca741f.png)

Labels to be added:
Scenario label: SCPTest-cloudin
Sprint Label: SCPTest-2211A
Landscape Label: trail2(Trial US East (VA) (AWS) )
Priority: High

Kindly look into this issue

Thanks & Regards,
Vinayak

**Comment by Karunaharan** [comment]
Hi @VinayakTamse01 
The issue is fixed and you should be able to execute the booster as expected.

Regards,
​Karuna

**Comment by VinayakTamse01** [comment]
Hi Karuna,

The issue is still there in same steps, failed to assign role collection using booster

Regards,
Vinayak
